title: Visual Weekly
description: A photo experiment
baseurl: "/vw"
url: "http://4711.gihub.io"

permalink: :title

markdown: kramdown

sass:
  style: :compressed
  sass_dir: assets/sass

exclude: [.gitignore, README.md, trigger-build.txt]

future: false
